### PR TITLE
Surgeon class and subclass icons

### PR DESCRIPTION
**Pull request by GentlemanBabbo**
Request to add Surgeon icon integration.

Mod is posted to Nexus currently; https://www.nexusmods.com/baldursgate3/mods/6111

Please tell me if I'm doing this wrong in anyway; I am super new to all of this.

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Heya,

What's happening with Dispoiler? should it be added too?

What about the action resource?

These can just be added without a dedicated class icon via the dynamic process - https://bg3.wiki/wiki/Modding:Modding_class_icons#Option_1:_Dynamic_(Easy)

Just change the folder structure from "Public\Game\GUI\Assets\Surgeon\ClassIcons" to "Public\Game\GUI\Assets\ClassIcons"

**Comment by GentlemanBabbo** [comment]
Hi! 

So despoiler was initially part of the plan, but after working really hard on Cannibal and Injector, I sort of had Despoiler take a back seat and didn't really think about it since I took out the code needed to reference it in game. I also couldn't figure out how to implement an action resource so I scrapped that. I probably should have cleaned those out of the code, so my apologies there.

I'm honestly new to all this; what would be your suggestion on my next steps?

**Comment by TheRealDjmr** [comment]
I'm just saying that you don't need the entries if you use the dynamic folder structure - 
[Surgeon Class Mod.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/14029494/Surgeon.Class.Mod.zip)



I would say that your main class icon is too big - 300x300 is the Larian sizing, but there's not a lot going on at the top and bottom of those images, so there's no clipping issues compared to yours.

But yeah let me know if you intend to keep it as-is and merge your entries into ImprovedUI, or just use the dynamic folder structure

**Comment by GentlemanBabbo** [comment]
That's really great to know about the size; thank you for that. I would have never known. I'll shrink it down. I'll try the dynamic structure too; if I run into any issues, is it alright if I reach back out?

**Comment by TheRealDjmr** [comment]
Feel free to reach out on Discord or here

**Pull request closed without merging**
