### PR TITLE
Added Rat King Ranger Icon

### PR DESCRIPTION
**Pull request by midnightvoyager**

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Hi @midnightvoyager do you have something we can test it with?

You can also use the dynamic option, rather than relying on a UI entry - https://bg3.wiki/wiki/Modding:Modding_class_icons

**Comment by TheRealDjmr** [comment]
Closing due to no response

**Comment by midnightvoyager** [comment]
Sorry, I've been kinda busy with Christmas and food poisoning. I couldn't get the dynamic method to work, even though I did what the instructions said to do. The documentation for GitHub is a labyrinthine nightmare, but I managed to get it set up to use it, and the icon at least works that way.

By something to test with, you mean the mod itself? This is it.
[RatKing.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13760437/RatKing.zip)
 I haven't released it yet because the icon is a dumb placeholder. A friend is making the actual icon I'll use.

**Comment by midnightvoyager** [comment]
@TheRealDjmr Are you still getting replies to this? I just went ahead and released the thing, but the version I attached has a test icon in it and that one has no icon at all.

**Comment by TheRealDjmr** [comment]
Sorry, looks like your previous response was missed due to the festive period, I've reopened the PR and taken a look

The dynamic method won't work currently due to the placement of the icons and the icon file names. They'd have to be in Public\Game\GUI\Assets\ClassIcons instead of Public\Game\GUI\Assets\ClassIcons, and both have the name "RatKing.DDS"

It works currently with the file structure in place, so let me know if the new icon is going to be named/located in the same place

**Comment by midnightvoyager** [comment]
I honestly don't know what went wrong on my end. I did the same thing and it didn't work, then I did the same thing with new images and it worked.

**Comment by TheRealDjmr** [comment]
Just checking then - is it working via dynamic, or still requiring the entry?

**Comment by midnightvoyager** [comment]
I've got it working dynamic. Sorry for the trouble! I don't know why it went wrong when I tried it before.

**Comment by TheRealDjmr** [comment]
No worries, let me know when the update is live and I'll add the mod to the supported mods list

**Comment by midnightvoyager** [comment]
Hi, I know this was forever ago, but life things happened. https://www.nexusmods.com/baldursgate3/mods/5514 I got my icon working

**Pull request closed without merging**
