### PR TITLE
BG3ImprovedUI_DevilAscendant_Icons

### PR DESCRIPTION
**Pull request by ThekingDude**

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Heya, got something we can test with?

**Comment by ThekingDude** [comment]
[Devil.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13879129/Devil.zip)

Do you need a copy of the pak file?

**Comment by ThekingDude** [comment]
sorry besides downloading files im new to Github

**Comment by TheRealDjmr** [comment]
Ta

**Comment by TheRealDjmr** [comment]
https://bg3.wiki/wiki/Modding:Modding_class_icons
You're using the dynamic file path, so no entry is needed in ImprovedUI:

**Pull request closed without merging**
