### PR TITLE
Pull request for new resource icon

### PR DESCRIPTION
**Pull request by pewpewzap**
Am I doing this right?

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
What's the mod? I'd want to test it first

**Comment by pewpewzap** [comment]
> What's the mod? I'd want to test it first

Sorry, it hasn't been released yet. Should I release first then send a pull request?

**Comment by TheRealDjmr** [comment]
I just want something to test with before pushing. If it's not released you can send it over Discord etc

**Comment by pewpewzap** [comment]
[Assets-20231031T031207Z-001.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13211620/Assets-20231031T031207Z-001.zip)

Would this assets folder suffice or will you need the entire mod?

**Comment by TheRealDjmr** [comment]
https://www.nexusmods.com/baldursgate3/mods/3769

**Review by TheRealDjmr — CHANGES_REQUESTED** [review]
Sent over Discord - looks like an issue with the DDS files

**Comment by TheRealDjmr** [comment]
Still having issues with the icon, let's put the entries in and the DDS issue can be fixed after Assets have released

**Comment by TheRealDjmr** [comment]
Actioned on https://github.com/TheRealDjmr/BG3ImprovedUI/pull/190

**Pull request closed without merging**
