### PR TITLE
mystic res icons (psipoints +psionicmasterycharge)

### PR DESCRIPTION
**Pull request by RichardAPena**
Class resource icons for Mystic (Psi Points and Psionic Mastery Charges)
Keyboard only

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Hey, what's the mod? This one? https://www.nexusmods.com/baldursgate3/mods/2786

**Comment by RichardAPena** [comment]
> Hey, what's the mod? This one? https://www.nexusmods.com/baldursgate3/mods/2786

Yep, that's the one, I'm Xhevo the mod creator.

**Comment by TheRealDjmr** [comment]
There's already a "PsiPoint" action resource icon. Can you add something to differentiate yours? Something like MysticPsiPoints

**Comment by RichardAPena** [comment]
There aren't any conflicts right now and it works in game, but sure I can do that

**Comment by TheRealDjmr** [comment]
No need to change your typeid or your files etc just the entries in the PR

PsiPoints -> MysticPsiPoints
PsiPointsGroup -> MysticPsiPointsGroup

Yeah it's not causing an issue now, but just for maintaining ImprovedUI it'll just make it a lot easier

**Comment by RichardAPena** [comment]
Just pushed some changes, hope everything is good now

**Comment by TheRealDjmr** [comment]
The CC versions of the icons aren't in your mod? It's fine if you don't have entries in IUI_ActionResourceIcons_k.xaml as I copy over the tooltip icon if you don't provide an entry there

image
image

**Comment by RichardAPena** [comment]
I haven't pushed the update with them yet, but they do show up in CC and level up
image

**Comment by TheRealDjmr** [comment]
Including in this update then

**Pull request merged**
