### PR TITLE
Update IUI_ClassIcons.xaml

### PR DESCRIPTION
**Pull request by GawDamnit**
Requested integration of new subclass icon entries for Vanguard subclass. Is testable with the latest version of the mod available on Nexus.

https://www.nexusmods.com/baldursgate3/mods/3686?tab=description

### CODE REVIEW

**Comment by GawDamnit** [comment]
Hey, noticed you popped in to comment on an icon size issue on my Nexus page. Thanks for that.

My issue is that when I resize the hotbar icons to 150x150 (or 140x140, as I've seen in other mods), nothing shows up at all in-game. I'm at a bit of a loss as to how to fix this. I've submitted the new subclass icons as 140x140, though. I just don't know how to fix the other ones.

In case it's related, I've tried to use the Dynamic method for getting class icons into the game and never could get it to work. I've checked over and over to make sure I'm using the right pathing, naming and imagine dimensions. Lostsoul on the Larian Discord took a look at it with me too and didn't see anything wrong.

**Comment by TheRealDjmr** [comment]
If you already have entries in ImprovedUI Assets, the dynamic method won't work. The entries would need to be removed first

I've resized the icons in ImprovedUI if they're too big:


Your new icons are working fine for me:

**Comment by GawDamnit** [comment]
Thank you very much! Does this mean I don't need to do anything on my end to fix the oversized icons now?

**Comment by GawDamnit** [comment]
Oh never mind, I just resized it on my end and it works now. Thanks for everything :)

**Pull request merged**
