### PR TITLE
Bloodline Point Action icon and subrace icons for HalfDragon

### PR DESCRIPTION
**Pull request by jodarkrider**
Action Resource icons and new subrace icons for HalfDragon mod.

### CODE REVIEW

**Comment by jodarkrider** [comment]
FYI, I'm pushing ahead of my mod update on Nexus, I can send it to you, in case you want to test. :) But I've tested it myself. :D

**Comment by jodarkrider** [comment]
New version of my mod is up now, in case you need to verify functionality! :)

**Comment by TheRealDjmr** [comment]
URL to mod:
https://www.nexusmods.com/baldursgate3/mods/2634

Status: UNVERIFIED

TODO:
Check mod with entry changes to confirm
Take screenshot of icon working
Merge with main and prep in release

**Comment by jodarkrider** [comment]
> URL to mod: https://www.nexusmods.com/baldursgate3/mods/2634
> 
> Status: UNVERIFIED
> 
> TODO: Check mod with entry changes to confirm Take screenshot of icon working Merge with main and prep in release

I'm currently enjoying vacation with my husband, so can't send those to you. I'll be back on 2nd July. :)

**Comment by TheRealDjmr** [comment]
> > URL to mod: https://www.nexusmods.com/baldursgate3/mods/2634
> > Status: UNVERIFIED
> > TODO: Check mod with entry changes to confirm Take screenshot of icon working Merge with main and prep in release
> 
> I'm currently enjoying vacation with my husband, so can't send those to you. I'll be back on 2nd July. :)

Enjoy your vacation, I know how important it is :)

I've added these notes to help me plow through these requests, that's all. No action required on your end!






What's the story with the half dragon "of x colour" race icon entries? Are they not needed any more?

**Comment by TheRealDjmr** [comment]
I'll leave the unused race icon entries in for now at least

**Pull request closed without merging**
