### PR TITLE
Illrigger class icons

### PR DESCRIPTION
**Pull request by CovelissLyvain**
Additions for Illrigger class mod (https://www.nexusmods.com/baldursgate3/mods/5876). Let me know if anything needs to be added/changed.

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Heya, few questions with this one. Why are we not adding the subclass icons at the same time?

I see you've set the extensions as .dds, which _does_ work but isn't what Larian uses - .DDS filenames and .png in the entries instead. The .png files do nothing. Are you keeping them as they are or aligning with Larian?

**Comment by CovelissLyvain** [comment]
Subclass icons and their respective hotbar icons should be lines 719 thru 729 and 899 thru 909. Are they not visible to you?

Didn't notice that Larian used .png for the the entries. I've updated any .dds references for my mod in this file to .png instead.

**Comment by TheRealDjmr** [comment]
Yep, they're coming through now, they didn't until your recent changes

You would also need to update your icon file names to .DDS for these entries to work too

**Comment by TheRealDjmr** [comment]
Interesting, selecting your class in CC is crashing the game for me after repacking. Here's ImprovedUI Assets with your class icons for testing - 
[ImprovedUI Assets.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13932188/ImprovedUI.Assets.zip)

**Comment by TheRealDjmr** [comment]
Looks like the mod clashed with another since it's working now. You might want to resize the main class icon - compared to Larian ones it's a bit big

**Pull request merged**
