### PR TITLE
I made some icons for Sneak Attack Charges 

### PR DESCRIPTION
**Pull request by genderwithyourmom**
Hi, first time making a pull. Am I doing it right? What is code?
Ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

[SNEKUI.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/15097206/SNEKUI.zip)

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Ah


Icon doesn't show in CC/Level up so the _k entry does nothing

**Comment by genderwithyourmom** [comment]
Oh ofc! I'll remove the CC for the main mod! Thanks for your help <3

**Comment by genderwithyourmom** [comment]
Question regarding publishing the mod since it makes little sense publish t out before the new Assets have been uploaded, but I also guess it would be nice for you to have a Nexus link to refer to for that very update.

Am I allowed to publish the mod with a modified AssetsEdit.pak file down in the optional files untill your update comes out?

**Comment by TheRealDjmr** [comment]
Please don't distribute an alternative copy of ImprovedUI Assets, it becomes a nightmare having to manage different versions

I'll get the assets update out today - I try to keep the updates to once a week max, and Friday/Saturday is the best time for it

**Comment by TheRealDjmr** [comment]
I've just updated ImprovedUI Assets

**Comment by genderwithyourmom** [comment]
You are an absolute star! The mod can be found at https://www.nexusmods.com/baldursgate3/mods/8973 now 💜

**Pull request merged**
