### PR TITLE
Announcement - no further PRs will be accepted until Patch 7

### PR DESCRIPTION
**Pull request by TheRealDjmr**
I can't explain why, but will have more info available closer to/when it drops

I will still work on existing PRs and requests/suggestions etc, but no further updates for Patch 6 after all existing PRs are merged

### CODE REVIEW

**Comment by Sumradagnoth** [comment]
Ah crap sorry I didnt see the announcement before I submitted my bad

**Comment by dbanks2010** [comment]
Hey, I know you can't explain why no more PRs until Patch 7, but just to be sure: can I still submit one and it'll be worked on for the Patch 7+ updates, or no? I just made an update for Additional Backgrounds and didn't realize this was a thing.

**Comment by TheRealDjmr** [comment]
Update - So more stuff is coming out about Patch 7 and there still seems to be a need for ImprovedUI Assets. Hopefully, changes will only be required in your copy of the mod, rather than requiring a pull request.

**Comment by Sumradagnoth** [comment]
Thanks for the update. Appreciate you keeping tabs on this

**Pull request closed without merging**
