### PR TITLE
Added SpellPointsResource for Wizard spell points project

### PR DESCRIPTION
**Pull request by Onyxeagle**
Hey! Thanks for the wonderful tool that IUI is. Creating a pull request for an icon for a spell points mod I've made.
See here: https://www.nexusmods.com/baldursgate3/mods/9931?tab=description

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
URL to mod:
https://www.nexusmods.com/baldursgate3/mods/9931

Status: UNTESTED

TODO:
Test mod with entry changes
Take screenshot(s) of every icon working (KB & C)
Merge with main and prep in release

**Comment by TheRealDjmr** [comment]
SpellSlotsResource is very generic - even something like SpellPointsWotCVariant is a better label of what it is and reduces any possibility of potential clashes

**Comment by TheRealDjmr** [comment]
The _k entry doesn't show - you'd need a corresponding progressiondescription entry for it to show

The name is fine I read it wrong

**Comment by Onyxeagle** [comment]
Hey Djmr,

That's a very good point - sometimes in the next few days I'll do some
renaming and fix things up

Cheers!

**Pull request merged**
