### PR TITLE
Action resource controller UI icons

### PR DESCRIPTION
**Pull request by 3XC4L1B3R**
+ my gem dragonborn subrace icons

It's necessary to create IUI_ActionResourceIcons_c.xaml because the same key as the hotbar icons is used by the controller UI for the resource bar icons.
I wasn't able to centralize all of the definition to that file, unfortunately.

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Yeah I'm thinking of doing it differently for controller icons

**Comment by TheRealDjmr** [comment]
Due to CTD issues I was unable to finish implementing this. Expect to see this in the next version

**Comment by TheRealDjmr** [comment]
I've just updated main, so you should be able to see some of the edits I've made

**Comment by TheRealDjmr** [comment]
Not sure if you're aware, but the race icons have already been added, ActionResourceTemplates_c would need to be a separate file as you have done but can carry over a lot more from DataTemplates_c. I'm going to reorganise it so that they can play nice (controller action resource tooltips need to be separate from keyboard action resources). Might not make Patch 3 initial release

**Comment by 3XC4L1B3R** [comment]
Thanks!
Can I request my changes from CCLib_k be added for the next release? This inconsistency bothers me:
Screenshot from 2023-09-18 16-02-45

**Comment by TheRealDjmr** [comment]
> Thanks! Can I request my changes from CCLib_k be added for the next release? This inconsistency bothers me: Screenshot from 2023-09-18 16-02-45

I was thinking of refactoring but I'm not expecting a lot of Dragonborn subraces so I'm including it in the next ImprovedUI

**Comment by TheRealDjmr** [comment]
Resolved with https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.10

**Pull request closed without merging**
