### PR TITLE
Race and deity icon for custom races

### PR DESCRIPTION
**Pull request by Lynstence**
If I'm doing something obviously wrong I'm so sorry - but I'm having a lot of trouble making the deity icons show up. The race icons fortunately do work on my end.

Adds 3 race icons, same image shared between race and its single subrace; 3 deity icons, 2 in solar, 1 in demon(and none of them seems to work).

Mod files:
[LAR_VariousPlayerRaces.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13978884/LAR_VariousPlayerRaces.zip)

The icons are all in the same format, resolution, all .DDS, etc. etc. so they should be good(?).
Screenshot 2024-01-18 111351

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Not sure why it wouldn't be working on your end, couldn't find any issues:

Here's a copy of ImprovedUI Assets with your entries in for testing - 
[ImprovedUI Assets (customraces test).zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/14029740/ImprovedUI.Assets.customraces.test.zip)
Maybe something was overwriting the entries you made? Should set priority to 20 when packing to overwrite the game at least

**Comment by Lynstence** [comment]
It seems removing the "mods" folder under game data did the trick. It now works on my end as well. 

The exact logistics are way over my head, but your confirming it does work was great help. Thank you for your patience. There shouldn't be any more trouble now.

**Comment by Lynstence** [comment]
On a different note, I've also forgotten to link the mods. It's my bad. Not sure if I can add comments after the fact, but if this info could be of any use, here:

Displacer player race: https://www.nexusmods.com/baldursgate3/mods/5002
Demon player race: https://www.nexusmods.com/baldursgate3/mods/3703
Solar player race: https://www.nexusmods.com/baldursgate3/mods/3861

**Comment by TheRealDjmr** [comment]
Ta I normally search nexus for them anyway, so saves a step

**Pull request merged**
