### PR TITLE
added icons for bloodhunter

### PR DESCRIPTION
**Pull request by Wolfe-tk**
https://www.nexusmods.com/baldursgate3/mods/2151

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
You've packed your mod with too high a priority, causing your mod to overwrite all class icons in ImprovedUI. 21 is sufficient to overwrite the base game files without overriding ImprovedUI.

I'll merge this in manually as part of the imminent Patch 3 update

**Comment by Wolfe-tk** [comment]
> You've packed your mod with too high a priority, causing your mod to overwrite all class icons in ImprovedUI. 21 is sufficient to overwrite the base game files without overriding ImprovedUI.
> 
> I'll merge this in manually as part of the imminent Patch 3 update

Thanks, I'll change it to 21 on the next update.

**Comment by TheRealDjmr** [comment]
Merged manually

**Comment by Wolfe-tk** [comment]
@TheRealDjmr just wanted to ping one more time to see if this could be merged for an upcoming release. I'm sure you're busy, just want to integrate when possible.

**Comment by Wolfe-tk** [comment]
lol
nevermind

**Comment by TheRealDjmr** [comment]
> @TheRealDjmr just wanted to ping one more time to see if this could be merged for an upcoming release. I'm sure you're busy, just want to integrate when possible.

Lol. Hopefully released tonight

**Comment by TheRealDjmr** [comment]
@Wolfe-tk Your icon is too big? Here it shows for multiclassing:
blood hunter multiclass

**Comment by Wolfe-tk** [comment]
@TheRealDjmr I'll take a look. It looks correct when it's the main class, but maybe I need to resize it for multiclassing. The integration with ImprovedUI is just to configure where to point it though right? I can just make the adjustment on my next release to change what needs to be changed.

**Comment by Wolfe-tk** [comment]
Fixed this. They were 300x300 instead of 140x140. Should be the right size in my next release tonight.

**Comment by Wolfe-tk** [comment]
@TheRealDjmr I set up my action resources identical to the Artificer implementation, but they don't seem to be showing up in game. Any errors you see?

**Comment by TheRealDjmr** [comment]
Wow, somehow I missed this one.

Looks like your action resource icons haven't worked for a while? I can't find a screenshot of them working.

Compared to every other working icon, you have action resource icons stored as .png instead of .DDS icons.

Reopening this - no action is required on the ImprovedUI end

**Comment by TheRealDjmr** [comment]
Yep, making them 48x48 .DDS files worked for me:

[c_ico_res_BloodMaledict.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13792606/c_ico_res_BloodMaledict.zip)

**Comment by Wolfe-tk** [comment]
> Yep, making them 48x48 .DDS files worked for me:  [c_ico_res_BloodMaledict.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13792606/c_ico_res_BloodMaledict.zip)

Hey thanks. I'll on updating those.

**Pull request closed without merging**
