### PR TITLE
Update IUI_BackgroundIcons.xaml for Additional Backgrounds

### PR DESCRIPTION
**Pull request by dbanks2010**
Added more background options

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Heya, do you have something to test the new icons with? I can't see any updates on Nexus

**Comment by dbanks2010** [comment]
I haven't updated Nexus yet, was waiting for this to update as I've done in the past.  I can publish it though if it makes it easier for you.

**Comment by dbanks2010** [comment]
Update has been published to Additional Backgrounds.
https://www.nexusmods.com/baldursgate3/mods/1874

**Comment by TheRealDjmr** [comment]
Entries have been added but not showing

Looking at filesize, they haven't been setup like the other .DDS files, and are possibly .png files renamed instead of using .DDS format.
I converted "Rewarded" into a .DDS file from my end and now it shows - so if you fix the DDS files in your mod, you should be good to go

**Pull request merged**
