### PR TITLE
IUI_DeityIcons.xaml

### PR DESCRIPTION
**Pull request by lostsoulman**
Add nine new gods

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
This is requesting that I put it at the top of the file structure rather than replace the existing IUI_DeityIcons.caml file

**Comment by lostsoulman** [comment]
Hi Djmr. Did I mess up the pull request again? Lol apologies

**Comment by lostsoulman** [comment]
Thanks, i change TheRealDjmr:main into what you posted?

**Comment by TheRealDjmr** [comment]
This needs to die in a fire

**Pull request closed without merging**
