### PR TITLE
Psi Warrior 

### PR DESCRIPTION
**Pull request by SixfingeredMage**
Lord Help Me :'(

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Wow you've been busy. Maybe I should turn off email notifications.

Your class icons are huge compared to Larian icons. This causes issues with the icon on the top right of CC, and when multiclassing. Check Fighter sizing as an example. I checked v1.2 of your mod so I don't know if you've changed them since.

On the other hand, I can't find the action resource icons referenced in your mod. I'd need something to test with and make sure it's all working

**Comment by SixfingeredMage** [comment]
Hey, thanks for the response! Do you mind if I message you on discord to
talk about it? Thanks :)

**Review by TheRealDjmr — CHANGES_REQUESTED** [review]
I see you've used Artificer as a base. You don't have to use the same settings as theirs.

For IUI_ActionResourceIcons_c.xaml - the controller icons are not placed in the relevant mod folder (Assets/PsiKnight/ActionResources_c...)

The controller icons should also be moved to that location within your mod

**Comment by TheRealDjmr** [comment]
Added manually and included in latest ImprovedUI Assets
https://github.com/TheRealDjmr/BG3ImprovedUI/pull/133/files

**Pull request closed without merging**
