### PR TITLE
Margerard0006 patch 1

### PR DESCRIPTION
**Pull request by Margerard0006**
Hey, terribly sorry if there's a lot of redundant notifications from me, this is my first time making any commit on GitHub let alone this mod specifically. I saw that I'm not on the pull request list even though I thought I did that too, so trying to make sure it's all correct and in the right place. Thank you so much for all your work!

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
No worries

Have you got something to test with? Your mod on Nexus doesn't have the icons in them currently.

**Comment by Margerard0006** [comment]
Ah, I didn't upload the mods yet because wasn't sure if I should before the icons get added here. I uploaded the new versions that have the icons to test with!

**Review by TheRealDjmr — CHANGES_REQUESTED** [review]
Took me a while to find out what the problem was

Your mod icons are stored in "icon_deities" instead of "icons_deities"
image
Just add the s and it'll work

**Comment by Margerard0006** [comment]
Ah, thanks for pointing that out! I did change the folder name privately now that I saw this, but it still seems to be only blank squares. Anything else I may have done wrong, other than the folder name? I also tried out both versions to see if it's caused by the naming difference (adding D to the deity tags version), but that didn't make a difference either

**Comment by TheRealDjmr** [comment]
I'm attaching a copy of your mod that works for me by tweaking the folder location. Your entry will be included in the next update of ImprovedUI Assets
[FaithfulFaithless.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/12939558/FaithfulFaithless.zip)

**Pull request merged**
