### PR TITLE
Alternate Monk Subclass Icons & ActionResource Icons (for keyboard)

### PR DESCRIPTION
**Pull request by OhhLoz**
Attempting to add Class Icon support and ActionResource icon support for [Alternate Monk](https://www.nexusmods.com/baldursgate3/mods/2266)

Apologies if I got anything wrong

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Aren't your class icons already supported via dynamic? Do they not already show in-game using ImprovedUI Assets?

I need something to test the action resources with, the icons aren't on Nexus yet. Is there anything you can send over?

**Comment by OhhLoz** [comment]
Yes they are, I added them in to the main as I was adding in ActionResource icons, if you want them to continue being supported by dynamic thats fine I just thought I would add them whilst I was making a pull request, apologies.
I included a zip of just the new icons (IUI.zip), an unpacked zip (AlternateMonkRAW.zip) and a packaged version (AlternateMonk.zip)

[IUI.zip](https://github.com/TheRealDjmr/B
[AlternateMonkRAW.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/12812569/AlternateMonkRAW.zip)
G3ImprovedUI/files/12812558/IUI.zip)
[AlternateMonk.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/12812571/AlternateMonk.zip)

**Review by TheRealDjmr — CHANGES_REQUESTED** [review]
In IUI_ActionResourceIcons_K, the CC icon entry is not contained within a folder to help determine which mod its from (Assets/AlternateMonk/CC/icons...)

**Comment by OhhLoz** [comment]
Hi, Sorry I was using the PsiPoint as a template, I considered using the Bladesinger one as I knew Expansion was what they used for their ModName. Should be fixed now

**Review by TheRealDjmr — COMMENTED** [review]
In the provided mod the icons are not stored in the same paths as listed here

AlternateMonk\Public\Game\GUI\Assets\Shared\Resources
Should be
AlternateMonk\Public\Game\GUI\Assets\AlternateMonk\Shared\Resources
within your mod too

**Comment by OhhLoz** [comment]
Yea Thanks, I was going to edit the file system when I released but this should be the correct file system
[AlternateMonkRAW.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/12837595/AlternateMonkRAW.zip)

**Comment by TheRealDjmr** [comment]
All done!

**Pull request merged**
