### PR TITLE
Illrigger Action resource icons

### PR DESCRIPTION
**Pull request by CovelissLyvain**
Added additions for my Illrigger class mod (https://www.nexusmods.com/baldursgate3/mods/5876). Please let me know if anything needs to be altered, etc...

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Looking over the request it's all good, just need answers to the same questions from #260

**Comment by CovelissLyvain** [comment]
Just updated .dds references to .png. I'll update my icon file names to .DDS as per #260

**Comment by TheRealDjmr** [comment]
Yeah they work once updating to .DDS - you might want to make them more visually distinct though. Very hard to see!!!

**Comment by TheRealDjmr** [comment]
You also have a controller icons folder, but no controller icon entries. Dedicated controller icons/entries are not required, but you have more flexibility over how icons appear in the action radial compared to keyboard

**Comment by CovelissLyvain** [comment]
Thanks for the feedback! Yeah, I'm definitely trying to figure out how to color the action icons or how to change them otherwise to make them more distinct. I'm not an art-inclined person, so it's definitely not my strong suit.

The controller folder(s) was included to basically set an aspirational goal for myself to make proper, separate controller/mouse & keyboard icons. I'm hoping to get to that soon!

Thank you so much for all your help and for the work you do!

**Pull request merged**
