### PR TITLE
Planetouched Race Icons

### PR DESCRIPTION
**Pull request by 0Lyra**

### CODE REVIEW

**Comment by 0Lyra** [comment]
Bumping

**Comment by TheRealDjmr** [comment]
Heya, I've been on an Easter break which is why there hasn't been much activity on my end. Plan is to go through requests this week, and release an update at the weekend.

**Comment by TheRealDjmr** [comment]
I can't find the mod on Nexus - is there anything I can test with? Feel free to reach out on Discord

**Comment by TheRealDjmr** [comment]
Mod requires a races.lsx entry for testing - unable to check without this

**Comment by TheRealDjmr** [comment]
Sorted

**Pull request merged**
