### PR TITLE
Action Resource Icons for Elemental Bender Class

### PR DESCRIPTION
**Pull request by spartandestroyr**
Added Several Resource Icons

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Heya, I can't find any Elemental Bender mod, sounds cool

I need something to test with before merging, feel free to reach out on Discord

**Comment by spartandestroyr** [comment]
> Heya, I can't find any Elemental Bender mod, sounds cool
> 
> I need something to test with before merging, feel free to reach out on Discord

**Comment by TheRealDjmr** [comment]
???

**Comment by spartandestroyr** [comment]
> ???

Hey I messaged in the discord but I’ll send here what I said there. Hey so I haven't finished the Elemental Bender class yet I basically built the base class and subclasses and added a single spell to test the ARPs but If all you need to do is test the icons I can send you that. If you need to test more than that it may be a little bit as I still need to create spells passives and progressions for everything

**Comment by TheRealDjmr** [comment]
It's not possible to ping me in the Discord server now, mods have removed that but you can DM.

Yep just need something to test the icons with

**Comment by spartandestroyr** [comment]
> It's not possible to ping me in the Discord server now, mods have removed that but you can DM.
> 
> Yep just need something to test the icons with

Okay no worries I’ll send that over when I get back home it most likely will be later today

**Comment by TheRealDjmr** [comment]
Looks like the class icon is slightly too big for CC

I don't like the blue border, would recommend toning it down

For Controller, the entries were incorrect

Worked after changing the entries (no changes required on your end)

**Comment by spartandestroyr** [comment]
I will make those fixes I'm not sure why the cc icon is so big it looked smaller on my screen but I'll make it smaller for sure

**Pull request merged**
