### PR TITLE
Trying to make action resources show up

### PR DESCRIPTION
**Pull request by SkyeBorne**
Cannot get them to show in testing. Copied the implementation of the vessel class as they are largely what I need. Not sure what I'm messing up and would appreciate a second look

### CODE REVIEW

**Comment by SkyeBorne** [comment]
The class mod itself is https://github.com/SkyeBorne/SB_ShamanLL if that is needed

**Comment by TheRealDjmr** [comment]
I'm guessing that when testing, you're not packing the UI changes at a high enough priority to overwrite. 20 overwrites the game, ImprovedUI uses higher priority on purpose.

From my end it's working:


I can't confirm that they are all working, as some of the action resources are not listed in progressions? So here's a copy of ImprovedUI Assets with your entries for testing - [ImprovedUI Assets.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13932303/ImprovedUI.Assets.zip)

**Comment by SkyeBorne** [comment]
Ok so 2/3 are working perfectly but the Evil Eye charge is showing up everywhere except the hotbar where it's still stars. Is there something wrong with that in particular?

Screenshot 2024-01-14 120459

**Comment by TheRealDjmr** [comment]
This shouldn't have "Slot" on the end
image

**Pull request merged**
