### PR TITLE
Bloodletter subclass icon added

### PR DESCRIPTION
**Pull request by 72division**
Adding Bloodletter rogue subclass icons. 
Many thanks. 

GitHub : https://github.com/72division/BG3_Bloodletter

### CODE REVIEW

**Comment by 72division** [comment]
Hi, please check the details and consider my request. 
Thanks.

**Comment by TheRealDjmr** [comment]
Heya, no worries.

I've had a look at the Git repository and found a few issues:
1. You have Class icons listed in both Dynamic and Direct paths. You only need one or the other - https://bg3.wiki/wiki/Modding:Modding_class_icons
2. You don't have any action resource icons located in Assets/Bloodletter/Shared/Resources/ - you only have the controller icon location only.

Also, the "Source" entries in ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml are just wrong, they just need to point to your controller action resource icon.

**Comment by 72division** [comment]
Hi, thanks for your guides. I have fixed the mistakes. Please check the details.
Have a good one!

**Comment by TheRealDjmr** [comment]
Thanks for the interest, I try to get updates out every Friday/Saturday around my free time and dropping new features. Since I've released the majority of the updates, it all falls upon me. Happy to have any help!

Yesterday I fixed the final issues I found to your entries and downloaded a copy of your mod from your repository, packed ready for testing.

Today I've tested both icon sets:

The action resource images are not setup correctly - The file extension is set to .dds instead of .DDS (like your class icons are), they are set to 50x50 instead of 48x48, and don't even show unless I recreate the .DDS file (maybe its an issue with how you're generating .DDS images?). Here's a screenshot after I resized your default icon and changed the paths for keyboard:

and how things currently look for controller users, with your supplied icons, even after I updated the file path locally:


Here's the resized and recreated icon as an idea of what works - 
[ico_classRes_BloodEssence.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13846822/ico_classRes_BloodEssence.zip)

Controller icons can actually be bigger - up to 80x80 depending on how you want them displayed for tooltips, but 50x50 should be fine (they are resized to 50x50 for the action radial if you want them like how others have entered them)

**Comment by TheRealDjmr** [comment]
Here's a copy of ImprovedUI Assets with the test entries so you can check it out from your end - 
[ImprovedUI Assets (bloodletter test).zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13846890/ImprovedUI.Assets.bloodletter.test.zip)

**Comment by TheRealDjmr** [comment]
The entries with .dds extensions are included in #250

**Comment by 72division** [comment]
> Here's a copy of ImprovedUI Assets with the test entries so you can check it out from your end - [ImprovedUI Assets (bloodletter test).zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13846890/ImprovedUI.Assets.bloodletter.test.zip)

Thanks for your help! I`m going to fix other icons.

**Comment by TheRealDjmr** [comment]
As mentioned yesterday, I dropped the ImprovedUI Assets update today. This includes the bloodletter entries as above. Keeping this open until the icons are sorted

**Comment by 72division** [comment]
I think I have fixed .dds issues. Can you kindly check my pak file again? 
Here`s link : https://github.com/72division/BG3_Bloodletter/blob/626b23c5047df94f9e797ce5f8abf321ab517b66/Bloodletter.pak

Many thanks.

**Comment by TheRealDjmr** [comment]
You should be able to check it too though, since the entries are in the latest version


I've added Bloodletter to the list of supported mods

**Pull request closed without merging**
