### PR TITLE
Harlequin Class Mod Support

### PR DESCRIPTION
**Pull request by harlequinzeg0**

### CODE REVIEW

**Review by TheRealDjmr — CHANGES_REQUESTED** [review]
Can you store the Asset files into your own mod via the same location? I am in the middle of removing the currently hosted icons, they will still work if stored in the same folder location within your mod

**Comment by harlequinzeg0** [comment]
Will do!

**Comment by harlequinzeg0** [comment]
Assets have been removed.

**Comment by TheRealDjmr** [comment]
Hey, what's the class mod? I can't find it to test with

**Comment by harlequinzeg0** [comment]
It's still being worked on; I know my pull request works. Hoping to release soon

image

**Pull request merged**
