### PR TITLE
Update IUI_ClassIcons.xaml

### PR DESCRIPTION
**Pull request by GawDamnit**
Requesting integration for Shadow Adept subclass icons for my Vanguard class mod.

The subclass is still in development and isn't a part of an existing version on Nexus. I've uploaded a testable version here.

[VanguardClass.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/13975026/VanguardClass.zip)

Many thanks as always!

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
All good apart from the typeid

**Comment by GawDamnit** [comment]
Thanks!

**Comment by GawDamnit** [comment]
Hello! Was this included in the latest ImprovedUI Assets release today? I downloaded and tested it and for some reason it wasn't working for me.

**Comment by TheRealDjmr** [comment]
I didn't apply the change to my local file when packing. 3.17.3.1 has the entry now

**Comment by GawDamnit** [comment]
No worries! Looks great on my end now. Thanks a bunch.

**Pull request merged**
