### PR TITLE
Pull request to add WoWDeathKnightClass UI components

### PR DESCRIPTION
**Pull request by lvlsortiara**
Hi there, thanks for maintaining this for the whole BG3 modding community. Your hardwork is greatly appreciated. This pull request is for adding the ClassIcon/ActionResourceIcon for the WoWDeathKnightClass:
https://www.nexusmods.com/baldursgate3/mods/1725

Below is a summary of all the changes I made to the main branch, please note that I added two .xaml files from Patch 2 that controls my ActionResource Icons under controller mode. I noticed that your mod currently don't have a structure for modding controller UI components, so I just uploaded the modified .xamls files. Please let me know if you have developed a cleaner way to do this, and I'll be more than happy to make the changes. Thanks again for your time and help!

Changes made to **_IUI_ActionResourceIcons.xaml_**:
```
1.  Added DK ActionResourcePath img file path (Line 44 - 55)
2.  Defined DK ActionResource data triggers (Line 125 - 176)
3.  Added DK ActionResrouceGroup definitions (Line 233 - 271)
4.  Added DK ActionResrouce Hotbar icons (Line 360 - 407)
```

Changes made to **_IUI_ClassIcons.xaml_**:
```
1. Added DK class and subclass icons (Line 99 - 110)
2. Added DK class and subclass hotbar icons (Line 198 - 209)

```
Added two files that modifies ActionResource UI under controller mode (both are from Patch 2):

Changes made to **_ActionResourceTemplates_c.xaml_**:
```
1. Modified DK ActionResource Cost preview under controller UI (Line 362 - 392)
```

Changes made to **_DataTemplates_c.xaml_**:
```
1. Added DK ActionResourceGroup definitions (Line 300 -338)
2. Modified DK ActionResrouce Icons to be stackable under controller UI (Line 1700 - 1736)
```

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Can you store your icons within a subfolder of assets following the structure of other icons added? Otherwise we can't associate entries to the mod they come from

Example:
Assets/deathknight/classicons/deathknight.dds

**Comment by lvlsortiara** [comment]
> Can you store your icons within a subfolder of assets following the structure of other icons added? Otherwise we can't associate entries to the mod they come from
> 
> Example: Assets/deathknight/classicons/deathknight.dds

Thanks for the reply, I thought subfolders were not needed since everything is moved to local mod folder.

Just updated all the codes and tested in game. Thanks!

**Comment by TheRealDjmr** [comment]
Thanks

Subfolders are not required but it would be impractical to manage without that information

**Comment by lvlsortiara** [comment]
Hi There,

I was wondering if it will be less work for you if I just move the controler UI xamls to my local mod folder and keep only the _IUI_ActionResourceIcons_ and _IUI_ClassIcons_ in this pull request?

Please let me if that works for you, and I'll make the changes accordingly.

Thanks!

**Comment by TheRealDjmr** [comment]
It's fine, I had a lot to milestones to hit before releasing and your changes had conflicts, which I couldn't assist with whilst on mobile. I'm picking these up now

**Comment by TheRealDjmr** [comment]
Can you remove your conflicting files? These prevent icons from other mods, amongst breaking other changes I've done to the UI:
image

**Pull request merged**
