### PR TITLE
Short race icons

### PR DESCRIPTION
**Pull request by sydmeier**

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Hey, what's the mod? We need something to test the icons with. Feel free to reach out over Discord

**Comment by TheRealDjmr** [comment]
Also - you don't need to store the race icons in a separate folder per race, just per mod

**Comment by TheRealDjmr** [comment]
Entries aren't working:



Opened up Santa and Leprechaun - icons have .dds extension instead of .DDS extension. 

To fix it for Leprechaun - I had to change the image size to be 196x196, set the correct extension, and use the correct Race UUID "0b0ae995-e258-4e43-8fc7-4335af157673" in the IUI_RaceIcons entry - confirmed working after all this:


I'll leave this open until the UUIDs are corrected and I'll be happy to test again when they're ready

**Comment by TheRealDjmr** [comment]
[Santa Deity](https://trello.com/c/xeXO8iHI/196-santa-deity)

**Comment by sydmeier** [comment]
sorry for the trouble, I updated everything now, hopefully it should be working.

**Comment by TheRealDjmr** [comment]
UUIDs in provided entries are still not matching the updated mods?

**Review by sydmeier — COMMENTED** [review]
I added 2 more races, hope that is ok
https://www.nexusmods.com/baldursgate3/mods/9168
https://www.nexusmods.com/baldursgate3/mods/9186

**Comment by TheRealDjmr** [comment]
URL to mods:
https://www.nexusmods.com/baldursgate3/mods/8107  Leprechaun
https://www.nexusmods.com/baldursgate3/mods/8465  Kender
https://www.nexusmods.com/baldursgate3/mods/8122  Garden Gnome
https://www.nexusmods.com/baldursgate3/mods/8617  Ghostwise Halfling
https://www.nexusmods.com/baldursgate3/mods/8862  3 files, Desert Dwarf, Sunstone Gnome, Wild Halfling (no longer available)
https://www.nexusmods.com/baldursgate3/mods/9210 Desert Dwarf
https://www.nexusmods.com/baldursgate3/mods/9205 Sunstone Gnome
https://www.nexusmods.com/baldursgate3/mods/9211 Wild Halfling
https://www.nexusmods.com/baldursgate3/mods/9168 Kaihunga Osse Dwarf
https://www.nexusmods.com/baldursgate3/mods/9186 Alux Gnome

https://www.nexusmods.com/baldursgate3/mods/5086 Santa Deity

https://www.nexusmods.com/baldursgate3/mods/9546 Whisper Gnome (not listed)
https://www.nexusmods.com/baldursgate3/mods/9547 Tinker Gnome (not listed)

Status: UNTESTED

TODO:
Test every mod with entry changes
Take screenshot(s) of every icon working
Merge with main and prep in release

**Comment by TheRealDjmr** [comment]
Checked Santa Deity - https://www.nexusmods.com/baldursgate3/mods/5086

Icon is still not showing 


Opened mod. Deity icon is 196x214. Correct size for Deity is 196x196, same for races as above.



Here is a copy of the working icon as a comparison - [Santa.zip](https://github.com/user-attachments/files/15934145/Santa.zip)

**Comment by sydmeier** [comment]
Thanks for letting me know, I just uploaded the fixed icon

**Comment by TheRealDjmr** [comment]
Leprechaun & Kender - working


Garden Gnome - not working


Found file path was not the same as entry - "Assets\**GardenGnomeSub**\CC\**icon_races**\" instead of "Assets/**GardenGnomeSubrace**/CC/**icons_races**/". Fixed after changing the file path:


The quick fix here is just to mirror the same file path in your mod, unless you want to change the file path in your mod

**Comment by TheRealDjmr** [comment]
Santa Deity merged

**Comment by sydmeier** [comment]
Thanks, uploading the fix now

**Comment by TheRealDjmr** [comment]
Ghostwise Halfling - working


Desert Dwarf - not working

**Comment by TheRealDjmr** [comment]
All races where icons are not showing currently:
Desert Dwarf
Kaihanga
Wild Halfling
Garden Gnome (I downloaded the latest version)
Whisper Gnome
Alux
Sunstone Gnome
Tinker Gnome


I'm going to move forward with updating today and focus on future patches. Without reviewing each mod individually, it's probably one or more of the points that have previously been raised.

**Comment by sydmeier** [comment]
thanks. I uploaded fixes for all of these, except Wild Halflings, I'm not
sure what is wrong with the file

**Comment by TheRealDjmr** [comment]
Redownloaded mods apart from Wild Halflings

Working:
Garden Gnome
Desert Dwarf
Kaihanga
Whisper Gnome

Not working:
Alux
Sunstone Gnome
Tinker Gnome

**Comment by sydmeier** [comment]
thanks, fixed them
Alux
Sunstone Gnome
Tinker Gnome
Wild Halfling

**Comment by sydmeier** [comment]
thanks for your help and patiance with all of this. Everything is working great, but the Wild Halflings and I can't find what is wrong with that icon

**Comment by TheRealDjmr** [comment]
I used the same settings to recreate the DDS icon with the settings that always worked for me (

image
[WildHalfling.zip](https://github.com/user-attachments/files/15961685/WildHalfling.zip)

**Comment by sydmeier** [comment]
that worked! thank you for all your help

**Pull request closed without merging**
