### PR TITLE
Implement Action Resource Icons for upcoming Class Mod

### PR DESCRIPTION
**Pull request by yoshisman8**
Just a PR to implement icons for my upcoming Ki Warrior class mod (It's not up on Nexus but i can provide a .pak of the mod if the team needs to see the mod in action). It uses the existing Ki, Sorcery Point and Natural Recovery icons rather than new icons, as those are sufficient for me right now.

image

image

image

image

### CODE REVIEW

**Comment by yoshisman8** [comment]
I amended the class icons since they were not working fully, i'll make a separate Pull Request once those are working. Sorry

**Comment by TheRealDjmr** [comment]
Can you provide a .pak to test with? Feel free to reach out over Discord

Got a soft spot for dbz, this looks really good

**Comment by yoshisman8** [comment]
> Can you provide a .pak to test with? Feel free to reach out over Discord
> 
> Got a soft spot for dbz, this looks really good

Sure! Send me a Message Request (@vyklade) and just let me know it's you!

**Comment by yoshisman8** [comment]
The mod is now on [Nexus Mods](https://www.nexusmods.com/baldursgate3/mods/5677?tab=files) if further verification is needed.

**Comment by TheRealDjmr** [comment]
Nice one, so because you're using base icons you don't need half the entries that you made, just the same entries as Ki Point etc. I've been making the changes locally instead:



Should get an update out tomorrow, just keeping an eye on if Larian drops the latest hotfix

**Comment by TheRealDjmr** [comment]
Well your icons are working via the dynamic process as seen above, but you also have a 2nd entry for the direct process? I haven't added a direct entry since it's not currently needed.

Anyway, your action resources are all done in this branch anyway - #250 

You might want to check out the Death Knight class (FrostRune etc) for how to use an action resource with a lot of resources for controller - ki doesn't look the best as its using fallback formatting:

**Pull request closed without merging**
