### PR TITLE
Race and action resource icons for a race mod

### PR DESCRIPTION
**Pull request by Lethelessness**
Hello, I would like to add race and action resource icons for my not yet published mod. I'm not at all familiar with GitHub so I may be missing something, but I think this is all I have to commit?

Thanks.

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Yep that's right, I just need something to test with, to make sure the icons work. Feel free to reach out on discord etc

**Comment by Lethelessness** [comment]
> Yep that's right, I just need something to test with, to make sure the icons work. Feel free to reach out on discord etc

This is the file I work with; don't know if it's enough for testing:
https://drive.google.com/file/d/1-kkFo5N1OSAhpmwXOmdgu1AkX99QwVpX/view

**Comment by TheRealDjmr** [comment]
Yep all good, though I have to add the entries in manually

**Comment by TheRealDjmr** [comment]
Added in #253

**Pull request closed without merging**
