### PR TITLE
Remainder of Bladesong action resource icons

### PR DESCRIPTION
**Pull request by Celestro**
There were a few entries that were excluded with past few updates.

### CODE REVIEW

**Comment by TheRealDjmr** [comment]
Can you store these in Assets/Expansion/Shared/Resources

**Comment by Celestro** [comment]
Did it though testing on my end results in the resource not showing up. Not sure if you're working some kind of magic there though

**Comment by TheRealDjmr** [comment]
Oops, I didn't include the fix in 3.8.1 - https://github.com/TheRealDjmr/BG3ImprovedUI/blob/main/ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml

**Comment by Celestro** [comment]
Ah that explains why so many others were missing haha.

**Pull request merged**
